plugins {
    id 'java-library'
    id 'checkstyle'
    id('com.diffplug.spotless') version '8.4.0'
}

group = 'com.faforever.testharness'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    api 'org.slf4j:slf4j-api:2.0.16'
    api 'ch.qos.logback:logback-classic:1.5.16'
    api 'com.fasterxml.jackson.core:jackson-databind:2.18.3'

    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Checkstyle).configureEach {
    ignoreFailures = false
}

test {
    useJUnitPlatform()
}

spotless {
    java {
        googleJavaFormat().aosp()
        formatAnnotations()
    }
}